from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from typing_extensions import Annotated
from typing import TypedDict, List, Annotated
from langgraph.graph.message import add_messages
from langchain_core.messages import  BaseMessage
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import  interrupt
from pydantic import BaseModel, Field
from langgraph.graph import END, StateGraph, START
import operator


def get_agent(api_key):


    llm_groq= ChatGroq(model="llama-3.1-8b-instant", api_key=api_key)

    class OutputSchema(BaseModel):
        option1: str= Field(description="The first option generated by llm")
        option2: str= Field(description="The second option generated by llm")
        option3: str= Field(description="The third and last option generated by llm")

    llm_for_option= llm_groq.with_structured_output(OutputSchema)

    class AgentState(TypedDict):
        messages: Annotated[List[BaseMessage], add_messages]
        topic: str
        story: Annotated[List[str], operator.add]
        summery_of_story: str
        current_options: List[str]
        user_chose_option: str

    def story_generator(state: AgentState):
        prompt= ChatPromptTemplate.from_messages(
            [
                ('system', 'you are very good at creating stories for children.'),
                ('human', """write a story about the topic or any situation stated: {topic}.
                            Keep the length of the story about 200 words.
                            Don't complete the story and don't give it an end.
                            End the story like its middle of a big story and many things going to happen after this.""")
            ]
        )
        chain= prompt | llm_groq
        response= chain.invoke({'topic':state['topic']})
        return {'messages':[response], 'story': [str(response.content)]}

    def summery_maker(state: AgentState):
        prompt= ChatPromptTemplate.from_messages(
            [
                ('system', "You are good at summerizing stories while keeping each details."),
                ('human', """Write the summery of the story : {story}.
                            Maintain every context of the story while keeping it small during summerization.
                            Mention each charecters ame properly in the summery and their action in the story.""")
            ]
        )
        story=""
        for i in state['story']:
            story+= i
        chain= prompt| llm_groq
        response= chain.invoke({'story': story})
        return {'messages': [response], 'summery_of_story': str(response.content)}

    def option_generator(state: AgentState):
        prompt= ChatPromptTemplate.from_messages(
            [
                ('system', 'You are very good at creating story progression options from summery of the imcomplete story.'),
                ('human',"""This is the summery of the imcomplete story: {summery}.
                            Compose three options which contains three different
                            story lines and which gradually leads the imcomplete story
                            into an end.Make each option of very small line. The options 
                            are based on the summery of the current story progression.
                            Generate option1, option2 and option3.""")
            ]
        )
        chain= prompt| llm_for_option
        response= chain.invoke({'summery': state['summery_of_story']})
        
        return {'current_options': [response.option1, response.option2, response.option3]}

    def input_taker(state: AgentState):
        decision= interrupt({
            "type": "multiple choice",
            "reason": "The story needs to progress.",
            "options": state["current_options"],
            "instruction": 'Choose one option or choose END to end the story.'
        })

        return {'user_chose_option': decision}

    def option_router(state: AgentState):
        
        if state['user_chose_option'].strip().lower()== "end":
            return 'end'
        else :
            
            return 'continue'

    def story_finilizer(state: AgentState):
        prompt= ChatPromptTemplate.from_messages(
            [
                ('system', "You are good at creating an beautiful ending from the summery of the whole story."),
                ('human', """Given an imcomplete story summery: {summery}.
                            Write an ending maintaining the context fully.
                            Make the ending about 200 words.
                            Make the transition from the given summery and the ending story very smooth.""")
            ]
        )
        chain= prompt | llm_groq
        response= chain.invoke({'summery': state['summery_of_story']})
        return {'messages': [response], 'story': [str(response.content)]}

    def story_progresser(state: AgentState):
        prompt= ChatPromptTemplate.from_messages(
            [
                ('system', "You are good at creating instruction for a story."),
                ('human',"""Given the summery of an imcomplete story: {summery}.
                            Given the idea for next plot of the story: {option}.
                            Write an summery like prompt so that the story generator
                            understands the context and starts writing story progression
                            according to the current position of the story and the given future plot.
                            Menstion each charecter present in the summery and also their actions.""")
            ]
        )
        chain= prompt | llm_groq
        response= chain.invoke({'summery': state['summery_of_story'], 'option':state['user_chose_option']})
        return {'topic': str(response.content), 'messages':[response]}

    graph_builder= StateGraph(AgentState)
    graph_builder.add_node("story_generator", story_generator)
    graph_builder.add_node('summery_maker', summery_maker)
    graph_builder.add_node('option_generator', option_generator)
    graph_builder.add_node('story_finilizer', story_finilizer)
    graph_builder.add_node('story_progresser', story_progresser)
    graph_builder.add_node('input_taker', input_taker)

    graph_builder.add_edge(START , "story_generator")
    graph_builder.add_edge("story_generator", "summery_maker")
    graph_builder.add_edge("summery_maker", "option_generator")
    graph_builder.add_edge('option_generator',"input_taker")
    graph_builder.add_conditional_edges("input_taker", option_router, 
                                        {"end": "story_finilizer",
                                        "continue":"story_progresser"})
    graph_builder.add_edge("story_finilizer", END)
    graph_builder.add_edge("story_progresser","story_generator")

    check_pointer= MemorySaver()

    agent= graph_builder.compile(checkpointer=check_pointer)

    return agent